# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
